import type { Employee, Location, ScheduleWeek, TimeEvent, Timecard } from "./timeclock-types";

export const businessDate = "2026-06-04";
export const currentWeekStart = "2026-06-01";
export const nextWeekStart = "2026-06-08";

export const locations: Location[] = [
  {
    id: "loc-downtown",
    name: "Downtown Coffee Bar",
    address: "18 King Street, New York, NY",
    timezone: "America/New_York",
    weekStart: "Monday",
    graceMinutes: 5,
    noShowMinutes: 15,
    operatingHours: {
      Mon: "6:00 AM - 7:00 PM",
      Tue: "6:00 AM - 7:00 PM",
      Wed: "6:00 AM - 7:00 PM",
      Thu: "6:00 AM - 8:00 PM",
      Fri: "6:00 AM - 9:00 PM",
      Sat: "7:00 AM - 9:00 PM",
      Sun: "7:00 AM - 5:00 PM",
    },
    active: true,
  },
  {
    id: "loc-riverside",
    name: "Riverside Kitchen",
    address: "402 River Road, Hoboken, NJ",
    timezone: "America/New_York",
    weekStart: "Monday",
    graceMinutes: 5,
    noShowMinutes: 15,
    operatingHours: {
      Mon: "10:00 AM - 10:00 PM",
      Tue: "10:00 AM - 10:00 PM",
      Wed: "10:00 AM - 10:00 PM",
      Thu: "10:00 AM - 11:00 PM",
      Fri: "10:00 AM - 12:00 AM",
      Sat: "9:00 AM - 12:00 AM",
      Sun: "9:00 AM - 9:00 PM",
    },
    active: true,
  },
];

export const employees: Employee[] = [
  {
    id: "emp-maya",
    name: "Maya Chen",
    initials: "MC",
    avatarColor: "bg-emerald-600",
    pin: "1834",
    role: "manager",
    position: "Manager",
    active: true,
    assignedLocationIds: ["loc-downtown", "loc-riverside"],
    email: "maya@timeclock.demo",
  },
  {
    id: "emp-omar",
    name: "Omar Patel",
    initials: "OP",
    avatarColor: "bg-sky-600",
    pin: "2408",
    role: "employee",
    position: "Shift Lead",
    active: true,
    assignedLocationIds: ["loc-downtown"],
  },
  {
    id: "emp-jules",
    name: "Jules Rivera",
    initials: "JR",
    avatarColor: "bg-primary",
    pin: "6621",
    role: "employee",
    position: "Barista",
    active: true,
    assignedLocationIds: ["loc-downtown"],
  },
  {
    id: "emp-lena",
    name: "Lena Brooks",
    initials: "LB",
    avatarColor: "bg-amber-600",
    pin: "9052",
    role: "employee",
    position: "Cashier",
    active: true,
    assignedLocationIds: ["loc-downtown", "loc-riverside"],
  },
  {
    id: "emp-noah",
    name: "Noah Kim",
    initials: "NK",
    avatarColor: "bg-neutral-700",
    pin: "4187",
    role: "employee",
    position: "Cook",
    active: true,
    assignedLocationIds: ["loc-riverside"],
  },
  {
    id: "emp-priya",
    name: "Priya Singh",
    initials: "PS",
    avatarColor: "bg-rose-600",
    pin: "7340",
    role: "employee",
    position: "Server",
    active: true,
    assignedLocationIds: ["loc-riverside"],
  },
  {
    id: "emp-cam",
    name: "Cam Wallace",
    initials: "CW",
    avatarColor: "bg-violet-600",
    pin: "1190",
    role: "employee",
    position: "Barista",
    active: true,
    assignedLocationIds: ["loc-downtown"],
  },
  {
    id: "emp-ivy",
    name: "Ivy Morgan",
    initials: "IM",
    avatarColor: "bg-teal-600",
    pin: "3771",
    role: "employee",
    position: "Cashier",
    active: true,
    assignedLocationIds: ["loc-downtown"],
  },
  {
    id: "emp-sam",
    name: "Sam Torres",
    initials: "ST",
    avatarColor: "bg-orange-700",
    pin: "8088",
    role: "employee",
    position: "Server",
    active: true,
    assignedLocationIds: ["loc-riverside"],
  },
  {
    id: "emp-eli",
    name: "Eli Park",
    initials: "EP",
    avatarColor: "bg-zinc-500",
    pin: "0007",
    role: "employee",
    position: "Barista",
    active: false,
    assignedLocationIds: ["loc-downtown"],
  },
];

export const schedules: ScheduleWeek[] = [
  {
    id: "schedule-downtown-current",
    locationId: "loc-downtown",
    weekStartDate: currentWeekStart,
    published: true,
    publishedAt: "2026-05-29T15:30:00-04:00",
    updatedAt: "2026-06-04T08:05:00-04:00",
    shifts: [
      {
        id: "shift-dt-thu-open",
        locationId: "loc-downtown",
        day: "Thu",
        start: "11:00 AM",
        end: "4:00 PM",
        position: "Cashier",
        breakMinutes: 0,
        notes: "Counter support",
        warning: "open-shift",
      },
      {
        id: "shift-dt-thu-omar",
        locationId: "loc-downtown",
        employeeId: "emp-omar",
        day: "Thu",
        start: "6:00 AM",
        end: "2:00 PM",
        position: "Shift Lead",
        breakMinutes: 30,
      },
      {
        id: "shift-dt-thu-jules",
        locationId: "loc-downtown",
        employeeId: "emp-jules",
        day: "Thu",
        start: "7:00 AM",
        end: "3:00 PM",
        position: "Barista",
        breakMinutes: 30,
      },
      {
        id: "shift-dt-thu-lena",
        locationId: "loc-downtown",
        employeeId: "emp-lena",
        day: "Thu",
        start: "9:00 AM",
        end: "5:00 PM",
        position: "Cashier",
        breakMinutes: 30,
        warning: "overlap",
      },
      {
        id: "shift-dt-thu-cam",
        locationId: "loc-downtown",
        employeeId: "emp-cam",
        day: "Thu",
        start: "3:00 PM",
        end: "11:30 PM",
        position: "Barista",
        breakMinutes: 30,
        warning: "outside-hours",
      },
      {
        id: "shift-dt-fri-omar",
        locationId: "loc-downtown",
        employeeId: "emp-omar",
        day: "Fri",
        start: "6:00 AM",
        end: "2:00 PM",
        position: "Shift Lead",
        breakMinutes: 30,
      },
      {
        id: "shift-dt-fri-jules",
        locationId: "loc-downtown",
        employeeId: "emp-jules",
        day: "Fri",
        start: "1:00 PM",
        end: "9:00 PM",
        position: "Barista",
        breakMinutes: 30,
      },
    ],
  },
  {
    id: "schedule-downtown-next",
    locationId: "loc-downtown",
    weekStartDate: nextWeekStart,
    published: false,
    updatedAt: "2026-06-04T10:20:00-04:00",
    shifts: [
      {
        id: "shift-dt-mon-omar",
        locationId: "loc-downtown",
        employeeId: "emp-omar",
        day: "Mon",
        start: "6:00 AM",
        end: "2:00 PM",
        position: "Shift Lead",
        breakMinutes: 30,
      },
      {
        id: "shift-dt-mon-jules",
        locationId: "loc-downtown",
        employeeId: "emp-jules",
        day: "Mon",
        start: "8:00 AM",
        end: "4:00 PM",
        position: "Barista",
        breakMinutes: 30,
      },
      {
        id: "shift-dt-tue-lena",
        locationId: "loc-downtown",
        employeeId: "emp-lena",
        day: "Tue",
        start: "9:00 AM",
        end: "5:00 PM",
        position: "Cashier",
        breakMinutes: 30,
        warning: "high-weekly-hours",
      },
      {
        id: "shift-dt-wed-open",
        locationId: "loc-downtown",
        day: "Wed",
        start: "12:00 PM",
        end: "8:00 PM",
        position: "Cashier",
        breakMinutes: 30,
        warning: "open-shift",
      },
      {
        id: "shift-dt-fri-cam",
        locationId: "loc-downtown",
        employeeId: "emp-cam",
        day: "Fri",
        start: "2:00 PM",
        end: "12:30 AM",
        position: "Barista",
        breakMinutes: 30,
        overnight: true,
        warning: "outside-hours",
      },
    ],
  },
  {
    id: "schedule-riverside-next",
    locationId: "loc-riverside",
    weekStartDate: nextWeekStart,
    published: false,
    updatedAt: "2026-06-04T10:10:00-04:00",
    shifts: [
      {
        id: "shift-rv-mon-noah",
        locationId: "loc-riverside",
        employeeId: "emp-noah",
        day: "Mon",
        start: "10:00 AM",
        end: "6:00 PM",
        position: "Cook",
        breakMinutes: 30,
      },
      {
        id: "shift-rv-mon-priya",
        locationId: "loc-riverside",
        employeeId: "emp-priya",
        day: "Mon",
        start: "4:00 PM",
        end: "11:00 PM",
        position: "Server",
        breakMinutes: 30,
      },
      {
        id: "shift-rv-fri-open",
        locationId: "loc-riverside",
        day: "Fri",
        start: "6:00 PM",
        end: "12:00 AM",
        position: "Server",
        breakMinutes: 0,
        warning: "open-shift",
      },
    ],
  },
];

export const timecards: Timecard[] = [
  {
    id: "tc-omar-today",
    employeeId: "emp-omar",
    locationId: "loc-downtown",
    businessDate,
    status: "clocked-in",
    scheduledShiftId: "shift-dt-thu-omar",
    attendance: "on-time",
    clockIn: "5:58 AM",
    breakMinutes: 0,
  },
  {
    id: "tc-jules-today",
    employeeId: "emp-jules",
    locationId: "loc-downtown",
    businessDate,
    status: "on-break",
    scheduledShiftId: "shift-dt-thu-jules",
    attendance: "late",
    clockIn: "7:14 AM",
    breakMinutes: 18,
  },
  {
    id: "tc-maya-today",
    employeeId: "emp-maya",
    locationId: "loc-downtown",
    businessDate,
    status: "clocked-out",
    attendance: "unscheduled",
    clockIn: "6:25 AM",
    clockOut: "9:05 AM",
    breakMinutes: 0,
    edited: true,
  },
  {
    id: "tc-ivy-today",
    employeeId: "emp-ivy",
    locationId: "loc-downtown",
    businessDate,
    status: "clocked-in",
    attendance: "unscheduled",
    clockIn: "10:42 AM",
    breakMinutes: 0,
  },
  {
    id: "tc-noah-yesterday",
    employeeId: "emp-noah",
    locationId: "loc-riverside",
    businessDate: "2026-06-03",
    status: "clocked-out",
    attendance: "early",
    clockIn: "9:52 AM",
    clockOut: "6:11 PM",
    breakMinutes: 30,
  },
];

export const events: TimeEvent[] = [
  {
    id: "evt-1",
    employeeId: "emp-ivy",
    locationId: "loc-downtown",
    businessDate,
    time: "10:42 AM",
    action: "clock-in",
    source: "station",
  },
  {
    id: "evt-2",
    employeeId: "emp-jules",
    locationId: "loc-downtown",
    businessDate,
    time: "10:31 AM",
    action: "start-break",
    source: "employee_web",
  },
  {
    id: "evt-3",
    employeeId: "emp-maya",
    locationId: "loc-downtown",
    businessDate,
    time: "9:05 AM",
    action: "clock-out",
    source: "manager_edit",
  },
  {
    id: "evt-4",
    employeeId: "emp-omar",
    locationId: "loc-downtown",
    businessDate,
    time: "5:58 AM",
    action: "clock-in",
    source: "station",
  },
  {
    id: "evt-5",
    employeeId: "emp-jules",
    locationId: "loc-downtown",
    businessDate,
    time: "7:14 AM",
    action: "clock-in",
    source: "employee_web",
  },
];
